# Generated by Django 4.1.3 on 2023-01-17 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admindb',
            name='City',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Gender',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Mobileno',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Password',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='Username',
        ),
        migrations.RemoveField(
            model_name='admindb',
            name='image',
        ),
    ]
